server:
  port: 9527
eureka:
  instance:
    prefer-ip-address: true
    instance-id: gateway-9527.com
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
zuul:
  routes: # 添加路由映射
    consmer.serviceId: user-consummer
    consmer.path: /consmer/**
  prefix: /mydemo   #添加前缀
  ignored-services: "*"